### ISSUE TITLE
MetaGraphs equivalent

### ISSUE THREAD

**Issue by sbromberger** [helgee/ItemGraphs.jl#1]
```
using LightGraphs, MetaGraphs

g = PathGraph(4)
mg = MetaGraph(g)
# set :name labels 'a' through 'd'
for v in vertices(mg)
  set_indexing_prop!(mg, v, :name, 'a' - 1 + v)
end

# find shortest paths from vertex 'b'
p = dijkstra_shortest_paths(mg, getindex(mg, :name)['b'])

# enumerate the paths, translating into the labels
[(x -> props(mg, x)[:name]).(y) for y in enumerate_paths(p)]
```

returns
```
4-element Array{Array{T,1} where T,1}:
 ['b', 'a']     
 Any[]          
 ['b', 'c']     
 ['b', 'c', 'd']
```

**Comment by helgee** [comment]
Thanks @sbromberger!

Please do not get this wrong, I am greatly benefitting from LightGraphs. But the reason this package exists is that I consistenly fail to understand how I am supposed to work with the APIs in the LightGraphs ecosystem.

For example, I am currently test-driving MetaGraphs and do not get why the following code does not work:
```julia
using LightGraphs, MetaGraphs

struct Registry
    graph::MetaGraph{Int64,Float64}

    Registry() = new(MetaGraph(DiGraph()))
end

graph(reg::Registry) = reg.graph

reg = Registry()

function register!(reg::Registry, trans, from, to)
    mg = graph(reg)

    add_vertex!(mg)
    v1 = nv(mg)
    @show has_vertex(mg, v1)
    @show v1
    set_indexing_prop!(mg, v1, :scale, from)

    add_vertex!(mg)
    v2 = nv(mg)
    @show has_vertex(mg, v2)
    @show v2
    set_indexing_prop!(mg, v2, :scale, to)
end

register!(reg, "TAItoTT", "TAI", "TT")
register!(reg, "TTtoTAI", "TT", "TAI")
```

This will give me:
```
has_vertex(mg, v1) = true
v1 = 1
has_vertex(mg, v2) = true
v2 = 2
ERROR: KeyError: key 2 not found
```

The proper way forward would be for me to file issues and documentation PRs but I want to understand where my general confusion stems from first.

**Comment by sbromberger** [comment]
You've uncovered a bug in `add_vertex!` for metagraphs (rather, an omission). The way you should do this is to `set_prop!(mg, v1, :scale, from)` and `set_prop!(mg, v2, :scale, to)`, then when you're all done, `set_indexing_prop!(mg, :scale)` to set the indexing all at once.

The other way to do this is to create the graph with the correct number of nodes (if you know them beforehand). This will be much more efficient. Once you do that you'll be able to use your existing `set_indexing_prop!` code.

That said, this is worthy of a bug report, so I'll file one on your behalf. Should be an easy fix. Sorry it's so confusing, but we do intend for MetaGraphs to fit this exact use case :)

**Comment by sbromberger** [comment]
ref: https://github.com/JuliaGraphs/MetaGraphs.jl/issues/32

**Comment by helgee** [comment]
Thanks again, Seth!

I think you have given me the final hint as to what my problem is. My use cases generally revolve around building graphs incrementally which is not as well supported IMHO as the more performant case where the number of vertices is known.

For example, I would expect `add_vertex!` to return the id of the newly created vertex since I usually need to work with it afterwards.

**Comment by sbromberger** [comment]
> For example, I would expect add_vertex! to return the id of the newly created vertex since I usually need to work with it afterwards.

It used to do that but we felt that making it consistent with `add_edge!` was more important since `nv()` is constant-time.

In general, building these (or any) graphs incrementally is expensive relative to creating the vertices all at once. This is a function / side effect of the storage we use and the performance guarantees we have on access. Unfortunately there's not a whole lot we can do without using a ton more memory.

**Comment by helgee** [comment]
I see. My graphs are usually really small (N<20) so this should not be a problem, should it?

Anyways, I hope that this package can be replaces by MetaGraphs in the near future.

**Comment by sbromberger** [comment]
oh, < 20 vertices? You won't notice an issue. If you were dealing with, say, a million vertices, then it'd be another story. :)
